name: dailies
description: ''
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  get_it: ^8.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  sqlite3_flutter_libs: ^0.5.38
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
