name: Flutter CI

on:
  push:
    branches: ["v2"]
  pull_request:
    branches: ["v2"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dailies

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
